# Generated by Django 5.0.1 on 2024-12-05 06:32

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]


def create_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    User = get_user_model()

    if User.objects.exists():
        return

    superuser = User.objects.create_superuser(
        username="john",
        email="john@gmail.com",
        password="bunlong03",
        last_login=timezone.now(),
    )
    superuser.save()


operations = [migrations.RunPython(create_superuser)]
